<a href="https://colab.research.google.com/github/shakilgazi/Cinematch--The-Personalized-Movie-Recommendation-System/blob/main/mental_health.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

SEED = 42
pd.set_option("display.max_columns", None)

In [2]:
data = pd.read_csv('/content/drive/MyDrive/Data/mh_data/Mental_health_dataset/data.csv', delimiter='\t')

In [3]:
data

,Q1A,Q1I,Q1E,Q2A,Q2I,Q2E,Q3A,Q3I,Q3E,Q4A,Q4I,Q4E,Q5A,Q5I,Q5E,Q6A,Q6I,Q6E,Q7A,Q7I,Q7E,Q8A,Q8I,Q8E,Q9A,Q9I,Q9E,Q10A,Q10I,Q10E,Q11A,Q11I,Q11E,Q12A,Q12I,Q12E,Q13A,Q13I,Q13E,Q14A,Q14I,Q14E,Q15A,Q15I,Q15E,Q16A,Q16I,Q16E,Q17A,Q17I,Q17E,Q18A,Q18I,Q18E,Q19A,Q19I,Q19E,Q20A,Q20I,Q20E,Q21A,Q21I,Q21E,Q22A,Q22I,Q22E,Q23A,Q23I,Q23E,Q24A,Q24I,Q24E,Q25A,Q25I,Q25E,Q26A,Q26I,Q26E,Q27A,Q27I,Q27E,Q28A,Q28I,Q28E,Q29A,Q29I,Q29E,Q30A,Q30I,Q30E,Q31A,Q31I,Q31E,Q32A,Q32I,Q32E,Q33A,Q33I,Q33E,Q34A,Q34I,Q34E,Q35A,Q35I,Q35E,Q36A,Q36I,Q36E,Q37A,Q37I,Q37E,Q38A,Q38I,Q38E,Q39A,Q39I,Q39E,Q40A,Q40I,Q40E,Q41A,Q41I,Q41E,Q42A,Q42I,Q42E,country,source,introelapse,testelapse,surveyelapse,TIPI1,TIPI2,TIPI3,TIPI4,TIPI5,TIPI6,TIPI7,TIPI8,TIPI9,TIPI10,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,uniquenetworklocation,hand,religion,orientation,race,voted,married,familysize,major
0,4,28,3890,4,25,2122,2,16,1944,4,8,2044,4,34,2153,4,33,2416,4,10,2818,4,13,2259,2,21,5541,1,38,4441,4,31,2451,4,24,3325,4,14,1416,4,37,5021,4,27,2342,4,39,2480,3,6,2476,4,35,1627,3,17,9050,3,30,7001,1,11,4719,4,20,2984,4,36,1313,4,42,2444,4,1,9880,4,2,4695,4,5,1677,3,4,6723,4,3,5953,2,26,8062,4,12,5560,4,7,3032,2,29,3316,3,40,3563,4,23,5594,4,41,1477,1,18,3885,2,9,5265,4,19,1892,3,22,4228,4,32,1574,4,15,2969,IN,2,19,167,166,1,5,7,7,7,7,7,5,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,1,1,2,3,2,2,16,1,1,1,12,1,10,2,1,2,NaN
1,4,2,8118,1,36,2890,2,35,4777,3,28,3090,4,10,5078,4,40,2790,3,18,3408,4,1,8342,3,37,916,2,32,1537,2,21,3926,2,25,3691,4,26,2004,4,4,8888,3,27,4109,3,19,4058,4,12,3692,2,6,3373,1,23,6015,1,16,3023,2,22,2670,3,3,5727,1,39,3641,2,33,2670,2,7,7649,3,11,2537,3,5,2907,4,9,1685,3,41,4726,3,17,6063,2,20,3307,3,14,4995,3,38,2505,2,34,2540,2,31,4359,3,15,3925,4,13,4609,2,30,3755,2,42,2323,1,24,5713,2,8,1334,2,29,5562,US,2,1,193,186,6,5,4,7,5,4,7,7,1,5,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2,3,2,1,16,2,1,2,7,0,70,2,1,4,NaN
2,3,7,5784,1,33,4373,4,41,3242,1,13,6470,4,11,3927,3,9,3704,1,17,4550,3,5,3021,2,32,5864,4,21,3722,2,10,3424,1,36,3236,4,23,2489,1,34,7290,4,12,6587,4,22,3627,4,38,2905,2,18,2998,2,8,10233,1,16,4258,4,28,2888,3,4,59592,2,3,11732,4,2,8834,2,29,7358,1,30,4928,2,15,3036,1,19,4127,2,37,3934,2,26,10782,4,1,8273,3,39,3501,1,27,3824,4,25,2141,3,6,17461,4,24,1557,4,40,4446,4,42,1883,2,35,5790,2,14,4432,1,20,2203,4,31,5768,PL,2,5,271,122,2,5,2,2,5,6,5,5,3,2,1,0,0,1,1,0,0,0,0,0,1,0,0,1,1,1,2,3,2,2,17,2,1,1,4,3,60,1,1,3,NaN
3,2,23,5081,3,11,6837,2,37,5521,1,27,4556,3,28,3269,3,26,3231,4,2,7138,2,19,3079,3,31,9650,3,17,4179,2,5,5928,1,21,2838,1,20,2560,4,29,5139,2,22,3597,2,35,3336,3,10,4506,1,14,2695,1,25,8128,2,15,3125,1,6,4061,1,40,4272,1,12,4029,1,9,5630,1,18,30631,2,24,9870,4,4,2411,1,16,9478,3,1,7618,3,32,12639,3,34,5378,1,41,8923,2,38,2977,4,3,5620,1,7,16760,1,8,6427,2,39,3760,1,13,4112,3,42,2769,4,33,4432,4,30,3643,2,36,3698,US,2,3,261,336,1,1,7,4,6,4,6,1,6,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,3,2,1,13,2,1,2,4,5,70,2,1,5,biology
4,2,36,3215,2,13,7731,3,5,4156,4,10,2802,4,2,5628,2,9,6522,4,34,2374,4,11,3054,4,7,2975,3,14,3524,2,33,3033,4,23,2132,4,17,1314,4,16,3181,4,26,2249,3,19,2623,4,35,3093,4,38,7098,4,37,1938,4,15,3502,3,32,4776,3,18,4463,4,4,2436,2,40,4047,4,31,3787,4,42,2102,2,1,12351,4,3,2410,2,22,5056,4,39,3343,3,27,3012,4,20,3520,4,8,1868,4,25,2536,3,24,3725,4,30,2130,3,29,3952,3,21,10694,3,41,3231,4,12,3604,4,28,1950,3,6,6265,MY,2,1766,164,157,2,5,3,6,5,5,5,6,3,3,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,1,3,2,2,2,19,2,2,3,10,1,10,2,1,4,Psychology
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39770,2,31,3287,1,5,2216,3,29,3895,2,37,2767,3,39,1745,2,4,6424,1,36,3737,3,24,1977,1,18,4089,4,34,1816,2,26,1928,2,17,3159,4,32,2768,2,22,5785,1,25,3969,3,41,2113,4,27,1624,2,15,6759,4,35,9888,3,9,2343,4,19,1759,3,23,2726,1,21,2008,3,12,2311,2,7,5959,3,30,1881,2,2,7312,2,11,1952,3,20,2168,2,40,4783,4,28,2712,1,13,7607,2,33,3727,4,1,3085,1,3,2968,2,42,2968,4,8,2577,4,10,1945,2,14,1938,3,6,3176,1,38,1792,3,16,2969,GB,2,7,143,66,2,2,3,5,6,5,5,3,3,6,1,1,0,1,1,0,0,0,0,1,0,0,1,1,1,1,2,2,1,1,16,2,1,1,2,4,60,2,1,2,NaN
39771,3,14,4792,4,41,2604,3,15,2668,4,33,4609,3,17,2434,4,26,2503,4,34,2598,4,11,2133,3,13,10455,4,37,3251,4,18,2332,4,28,2406,4,5,3912,4,2,7770,4,12,3637,4,30,2633,3,20,2091,3,24,2241,4,36,6757,4,27,2592,4,25,3156,4,19,3559,3,21,2217,4,9,3058,3,4,9348,4,6,6105,3,8,3522,3,3,2725,3,29,3169,3,1,24667,4,31,3198,3,38,3542,3,40,3881,4,39,1644,3,42,8563,3,7,3244,3,22,4218,4,32,1734,3,23,2250,3,10,3327,3,16,5300,4,35,1967,MY,1,10,181,243,4,5,5,7,4,6,4,7,4,4,1,1,0,1,1,0,0,0,0,1,0,1,0,1,1,1,3,2,1,2,21,1,1,1,10,0,10,2,1,4,Mathematic
39772,2,1,25147,1,4,4555,2,14,3388,1,27,2753,1,6,5455,1,41,4938,1,24,3738,1,40,3820,2,28,10008,1,38,3670,1,5,9493,1,22,7407,2,2,13180,1,3,17016,1,36,2686,1,34,3370,1,35,3686,1,11,5174,1,20,4689,1,7,4139,1,19,3470,1,9,3335,1,8,2468,2,23,5053,1,18,11244,1,33,4922,2,16,6272,1,12,2968,2,15,8608,1,13,5939,2,42,3619,1,10,5623,2,29,2788,1,37,3236,1,21,5505,1,17,3788,1,32,5852,1,25,3253,2,26,5338,1,39,5906,1,30,3470,1,31,4607,US,0,12,246,257,6,6,7,5,6,3,6,1,5,4,0,1,0,1,1,0,0,0,0,1,0,0,0,0,1,1,3,2,2,1,48,2,1,1,7,1,30,1,2,3,Computer Science
39773,3,36,4286,1,34,2736,2,10,5968,2,20,5655,3,9,2296,3,16,2627,3,32,3143,4,2,3164,3,19,5568,1,41,2324,3,39,2766,3,26,2852,4,42,2121,4,27,3097,1,6,3663,1,24,11004,2,38,2672,3,8,2285,1,29,4014,2,22,2671,2,35,10759,4,4,2830,1,37,1999,2,5,4785,1,23,3803,3,25,2487,4,14,2496,3,18,8333,3,33,3763,1,17,7682,2,28,2946,3,12,3163,4,7,2287,2,11,9307,3,3,3688,2,31,1878,1,40,2797,2,1,7095,3,21,2844,2,30,6185,4,15,1865,3,13,4647,US,2,2,174,113,1,6,5,7,3,5,3,5,3,4,1,1,1,1,1,0,0,1,0,1,0,0,1,1,1,1,3,2,2,1,20,2,1,1,6,1,60,1,1,2,History
39774,2,28,32251,1,22,3317,2,4,11734,1,19,4659,4,32,4236,2,1,33800,1,3,7855,1,34,3151,1,31,12698,1,41,3656,3,13,2843,1,40,3681,3,7,4381,1,20,16269,1,36,2741,4,18,3819,4,14,2730,3,30,9398,4,8,19839,3,12,2921,4,2,6807,2,42,34632,1,37,2275,2,27,5026,2,16,22293,2,38,5087,3,23,23294,2,11,4667,3,9,5012,1,29,14627,2,33,6248,2,5,9402,2,26,4009,3,24,4033,2,6,26642,2,17,4894,2,39,9317,4,25,2478,3,10,19868,3,35,12200,1,21,3492,4,15,13954,MY,1,17,427,371,6,2,3,5,6,3,5,5,1,2,1,0,0,1,1,0,0,0,0,1,0,0,0,0,1,1,3,3,2,2,26,1,1,1,10,1,10,1,1,4,Cognitive Science

In [5]:
data.columns

Index(['Q1A', 'Q1I', 'Q1E', 'Q2A', 'Q2I', 'Q2E', 'Q3A', 'Q3I', 'Q3E', 'Q4A',
       ...
       'screensize', 'uniquenetworklocation', 'hand', 'religion',
       'orientation', 'race', 'voted', 'married', 'familysize', 'major'],
      dtype='object', length=172)